name: calendar
kind: pipeline

workspace:
  base: /project
  path: /src/github.com/CNSC2Events/calendar

steps:
- name: "testing"
# TODO
- name: "build"
  image: golang:1.13
  commands:
  - go build -o calendar main.go
  - rm main.go
