name: calendar
kind: pipeline

workspace:
  base: /project
  path: /src/github.com/CNSC2Events/calendar

steps:
- name: publish_dockerhub
  image: plugins/docker
  settings:
    repo: scnace/calendar
    auto_tag: true
    username:
        from_secret: DOCKERHUB_USER
    password:
        from_secret: DOCKERHUB_PASSWORD
    dockerfile: Dockerfile
